### ISSUE TITLE
프로젝트 시나리오 작성

### ISSUE THREAD

**Issue by sushin-42** [yellowRibbonToCode/PrivateLibrary#1]
.

**Comment by jinbekim** [comment]
example)
기자 시나리오
페르소나

40세, 남성, 공덕 거주, 정치 부문 기자 김바로씨
시놉시스

김바로씨(40세)가 살고 있는 지역은 서울시 공덕동이다.

니즈

알리고 싶은 내용을 많은 유저에게 노출시키고 싶다.
간편하게 기사 컨텐츠를 작성하고 싶다.
시나리오1

(기자)

'기자' 신분으로 회원가입을 한다.
기사 리스트 화면 상단 로그인 버튼을 클릭한다.
로그인 후 기사 작성하기 버튼을 클릭한다.
기사 에디터 화면에서 마크다운으로 콘텐츠를 작성하고, 이미지를 업로드한다.
미리보기 버튼을 클릭하면 앞서 작성한 콘텐츠가 어떻게 보여질지 확인할 수 있다.
임시저장 버튼을 누르면 미완성된 기사를 저장할 수 있다.
공개여부 토글을 통해 공개/비공개 여부를 정할 수 있다. 기본값은 '비공개'이다.
게시하기 버튼을 누르면 기사가 업로드된다.
기사 리스트 화면에서 내 기사 관리하기 버튼을 누르면 내가 작성한 기사 리스트를 확인할 수 있다.
기사 수정하기 버튼을 클릭하면 해당 기사의 컨텐츠가 채워진 기사 에디터 화면에 진입할 수 있다.
기사 삭제하기 버튼을 클릭하면.. 이건 논의해야할듯 :)
기사를 보는 유저
시나리오 2

(기사를 보는 유저)

페르소나

30세, 남성, 서교동 거주, 기사를 보는 유저 우인준씨
시놉시스

우인준(30세)씨가 살고 있는 지역은 서울시 서교동이다.

개발공부와 취업준비에 매달리다보니 뉴스를 접할 시간이 부족하다.

여력이 된다면 아침에 네이버 메인포털의 뉴스란을 확인한다.

그러나 아쉬운 점은 자극적이고 각 언론사별 성향에 평향된 제목과 내용 때문에

팩트 체크와 핵심 요약에 시간이 많이 쓰인다는 것이다.

시간이 부족할 수 록 점점 뉴스를 접하지 못하게 되어 아쉽다.

니즈

치우치지 않은 뉴스를 확인하고 싶다.
시간을 적게 쓰고 싶다.
핵심만 쉽게 확인하고 싶다.
사이트 이용 시나리오

아침에 기사가 업로드되었음을 알리는 메일을 확인한다.
링크를 클릭하여 기사 리스트 화면에 진입한다.
스크롤하여 기사 내용을 확인한다.
이 때 아래 항목이 확인 가능하다.
기사 제목
썸네일 이미지
기사 요약문
기자 이름
기사 업로드 시간
기사 카테고리
기사 상세보기 버튼
공유하기 버튼(SNS에 공유, 링크 생성)
자세히 보고 싶은 기사를 발견하고, 기사 상세보기 버튼을 눌러서 기사 내용을 확인한다.
이 때 '기사 리스트' 화면에서 확인가능했던 정보들 외에 아래 정보를 추가로 확인 가능하다.
기사 상세 내용
리스트로 돌아가기 버튼
기자가 글을 잘 쓰는 듯하여 해당 기자 이름을 클릭하여 기사 리스트를 확인한다.
'정치/사회' 카테고리가 마음에 들어서 해당 카테고리 명을 클릭하여 연관 기사들을 확인한다.
