### ISSUE TITLE
Bug: 주소등록이 안되있을 경우.

### ISSUE THREAD

**Issue by jinbekim** [yellowRibbonToCode/PrivateLibrary#101]
![image](https://user-images.githubusercontent.com/59330110/141740452-2791a199-185d-4b5b-8c50-10aa62e55ebb.png)
![image](https://user-images.githubusercontent.com/59330110/141740505-6abda60f-b3ff-4186-9447-0cc619194cde.png)

**Comment by hekang42** [comment]
옵셔널로 하면 해결되겠네요
