### ISSUE TITLE
자동로그인 시 로그인뷰 안보이게 수정

### ISSUE THREAD

**Issue by sushin-42** [yellowRibbonToCode/PrivateLibrary#106]

**Comment by hekang42** [comment]
앱 딜리게이트에서 필터링으로
유저 데이터가 있을경우 로그인 후 홈뷰로 전달

**Comment by hekang42** [comment]
UserDefaults.standard 값을 이용하여 해결 !

**Comment by hekang42** [comment]
https://stackoverflow.com/questions/50636098/how-to-login-user-automatically-in-ios-swift
